matrix:

  include:

    - language: go
      os:
        - linux
      go:
        - 1.14.x
      env:
        - DB_USER=root DB_PASSWD=''  DB_TNS='tcp(127.0.0.1:3306)'
      service:
        - mysql
      before_install:
        - mysql -e 'CREATE DATABASE wayne;'
      script:
        - pwd
        - echo '' >  /home/travis/gopath/src/github.com/Qihoo360/wayne/src/backend/conf/dev.conf
        - export GO111MODULE=on && export GOPROXY=https://mirrors.aliyun.com/goproxy/
        - cd src/backend && go run main.go

    - language: node_js
      os:
        - linux
      node_js:
        - 12.16.x
      before_install:
        - cd src/frontend && npm install
      script:
        - npm run build
        - npm run lint
